site_name: Developer Documentation
theme:
  name: 'material'
nav:
  - index.md
  - Agile:
    - Overview: agile.md
    - Principle: agile/principle.md
    - Planning: agile/planning.md
    - Success Story: agile/success_story.md
  - Ubuntu:
    - Overview: ubuntu.md
    - Command line: ubuntu/command.md
    - Bash scripts: ubuntu/bash.md
    - SSH: ubuntu/ssh.md
    - SSL:
      - Overview: ubuntu/ssl.md
      - Create SSL: ubuntu/ssl/ssl_create.md
      - SSL for Magento site: ubuntu/ssl/ssl_magento_setup.md
    - Note: ubuntu/note.md
  - Server:
    - Overview: server.md
    - Domain: server/domain.md
    - SSL: server/ssl.md
    - SSH: server/ssh.md
    - Note: server/note.md
  - Nginx:
    - Overview: nginx.md
    - Web Server: nginx/web_server.md
    - Reverse Proxy: nginx/reverse_proxy.md
  - Git:
    - Overview: git.md
    - Git Internals: git/internals.md
    - Note: git/note.md
  - Magento:
    - Overview: magento.md
    - Installation: magento/install.md
    - Framework:
        - Overview: magento/framework.md
        - Prepare: magento/framework/prepare.md
        - Build: magento/framework/build.md
        - Partial caching: magento/framework/partial_caching.md
        - Full page caching: magento/framework/page_caching.md
        - Module development: magento/framework/module_development.md
        - Note: magento/framework/note.md
    - Command line: magento/command.md
    - MFTF:
      - Overview: magento/test.md
      - Functional Testing:
        - Overview: magento/test/functional/index.md
        - Installation: magento/test/functional/install.md
        - Test Run: magento/test/functional/run.md
        - Create a Test - Theory: magento/test/functional/create_test_theory.md
        - Create a Test - Practice: magento/test/functional/create_test_practice.md
        - Functional Testing Framework Entities: magento/test/functional/entities.md
    - Install extension Magento by composer: magento/composer.md
    - Magento 2.3 - PWA Studio: magento/pwa_studio.md
    - Sample:
      - Overview: magento/sample.md
      - Magento 2 - Tags Input: magento/sample/tags_input_magento2.md
    - Preparation notes for Magento 2 Certified Professional Developer exam: magento/magento2_exam_notes.md
    - Note: magento/note.md
  - Docker:
    - Overview: docker.md
    - Install: docker/install.md
    - Get started: docker/get_started.md
    - Develop with Docker: docker/develop.md
    - Sample: docker/sample.md
    - Documents: docker/documents.md
    - Note: docker/note.md
  - Jenkins:
    - Overview: jenkins.md
    - Install: jenkins/install.md
    - Documents: jenkins/documents.md
    - Sample: jenkins/sample.md
    - Note: jenkins/note.md
  - Design Pattern:
    - Overview: design_pattern.md
    - Observer: design_pattern/observer.md
  - Mkdocs: mkdocs.md

markdown_extensions:
  - codehilite
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
